import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Sidebar for documentation
  docsSidebar: [
    "intro",
    {
      type: "category",
      label: "Installation",
      link: {
        type: "generated-index",
        title: "Installing Melify",
        description: "Learn how to install and set up Melify",
      },
      items: [
        "installation/prerequisites",
        "installation/local-setup",
        "installation/environment-variables",
        "installation/gmail-integration",
        "installation/start-melify",
      ],
    },
    {
      type: "category",
      label: "Features",
      link: {
        type: "doc",
        id: "ai-features",
      },
      items: ["ai-features"],
    },
    {
      type: "category",
      label: "Development",
      link: {
        type: "generated-index",
        title: "Development Guide",
        description: "Contribute to Melify and learn about its architecture",
      },
      collapsed: true,
      items: ["contributing", "architecture"],
    },
    {
      type: "category",
      label: "Deployment",
      link: {
        type: "doc",
        id: "deployment-guide",
      },
      items: [
        "deployment-guide",
        {
          type: "category",
          label: "Self-Hosted Deployment",
          items: [
            "self-hosted-deployment/architecture",
            "self-hosted-deployment/gcp-setup",
          ],
        },
      ],
    },
    "faq",
  ],

  // You can use this for an alternative auto-generated sidebar if needed
  // autoSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
